global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'retail-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

  - job_name: 'retail-dashboard'
    metrics_path: /metrics
    static_configs:
      - targets: ['dashboard:8501']

  - job_name: 'milvus'
    static_configs:
      - targets: ['vector-db:19121']